# Generated by Django 6.0.1 on 2026-01-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmployeeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("age", models.IntegerField(verbose_name="Age")),
                (
                    "employee_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Employee ID"
                    ),
                ),
                (
                    "department",
                    models.CharField(max_length=100, verbose_name="Department"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Employee Profile",
                "verbose_name_plural": "Employee Profiles",
                "db_table": "employee_profiles",
                "ordering": ["-created_at"],
            },
        ),
    ]
