# Generated by Django 6.0.1 on 2026-01-22 09:06

import django.db.models.deletion
from django.db import migrations, models


def create_departments_and_migrate_data(apps, schema_editor):
    """Create initial departments and migrate existing employee data."""
    Department = apps.get_model('profiles', 'Department')
    EmployeeProfile = apps.get_model('profiles', 'EmployeeProfile')
    
    # Create default departments
    departments_data = [
        {'code': 'TECH', 'name': '技术部', 'description': '技术研发部门'},
        {'code': 'HR', 'name': '人事部', 'description': '人力资源部门'},
        {'code': 'FIN', 'name': '财务部', 'description': '财务管理部门'},
        {'code': 'SALES', 'name': '销售部', 'description': '市场销售部门'},
        {'code': 'OPS', 'name': '运营部', 'description': '运营管理部门'},
    ]
    
    created_departments = {}
    for dept_data in departments_data:
        dept = Department.objects.create(**dept_data)
        created_departments[dept_data['name']] = dept
    
    # Migrate existing employee data
    # Get the old department name from the database directly
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT id, department FROM employee_profiles")
        employees = cursor.fetchall()
        
        for emp_id, old_dept_name in employees:
            # Map old department text to new Department object
            if old_dept_name in created_departments:
                new_dept = created_departments[old_dept_name]
            else:
                # If department not in default list, create it
                dept_code = old_dept_name[:4].upper()
                new_dept = Department.objects.create(
                    code=dept_code,
                    name=old_dept_name,
                    description=f'Auto-migrated from existing data'
                )
            
            # Update employee with new department_id (temporarily using raw SQL)
            cursor.execute(
                "UPDATE employee_profiles SET department_id_temp = %s WHERE id = %s",
                [new_dept.id, emp_id]
            )


def reverse_migration(apps, schema_editor):
    """Reverse the data migration."""
    Department = apps.get_model('profiles', 'Department')
    Department.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        # Create Department model
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Department Name"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Department Code"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "db_table": "departments",
                "ordering": ["name"],
            },
        ),
        
        # Add temporary department_id field (nullable)
        migrations.AddField(
            model_name="employeeprofile",
            name="department_id_temp",
            field=models.IntegerField(null=True),
        ),
        
        # Create departments and migrate data
        migrations.RunPython(
            create_departments_and_migrate_data,
            reverse_migration
        ),
        
        # Remove old department field
        migrations.RemoveField(
            model_name="employeeprofile",
            name="department",
        ),
        
        # Rename temp field to department_id
        migrations.RenameField(
            model_name="employeeprofile",
            old_name="department_id_temp",
            new_name="department_id",
        ),
        
        # Alter field to be ForeignKey
        migrations.AlterField(
            model_name="employeeprofile",
            name="department_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="profiles.department",
                verbose_name="Department",
                db_column="department_id",
            ),
        ),
    ]
