# Generated by Django 6.0.1 on 2026-01-22 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_company_multicompany_support"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeeprofile",
            name="department_id",
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="profiles.department",
                verbose_name="Department",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="email",
            field=models.EmailField(
                default="zihao.xu@example.com",
                max_length=254,
                unique=True,
                verbose_name="Email Address",
            ),
            preserve_default=False,
        ),
    ]
