# Generated by Django 6.0.1

from django.db import migrations


def create_users_for_existing_employees(apps, schema_editor):
    """Create Django User accounts for existing employees."""
    EmployeeProfile = apps.get_model("profiles", "EmployeeProfile")
    User = apps.get_model("auth", "User")
    
    # Get default password from validators
    default_password = "abc123"
    
    for employee in EmployeeProfile.objects.filter(user__isnull=True):
        # Create User with employee_id as username
        # Note: We can't use create_user in migrations, must use create and hash password manually
        from django.contrib.auth.hashers import make_password
        
        user = User.objects.create(
            username=employee.employee_id,
            email=employee.email,
            password=make_password(default_password)
        )
        
        # Link user to employee
        employee.user = user
        employee.save()
        
        print(f"Created user for employee: {employee.name} ({employee.employee_id})")


def reverse_migration(apps, schema_editor):
    """Remove created users."""
    EmployeeProfile = apps.get_model("profiles", "EmployeeProfile")
    User = apps.get_model("auth", "User")
    
    for employee in EmployeeProfile.objects.exclude(user__isnull=True):
        if employee.user:
            user_id = employee.user.id
            employee.user = None
            employee.save()
            User.objects.filter(id=user_id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_employeeprofile_user"),
    ]

    operations = [
        migrations.RunPython(
            create_users_for_existing_employees,
            reverse_migration
        ),
    ]
