# Generated by Django 6.0.1 on 2026-01-22 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0006_create_users_for_employees"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hub_capacity_limit",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Maximum number of tickets in the big hub",
                        verbose_name="Hub Capacity Limit",
                    ),
                ),
                (
                    "dept_receiving_box_limit",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Maximum number of tickets in each department's receiving box",
                        verbose_name="Department Receiving Box Limit",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Configuration",
                "verbose_name_plural": "System Configuration",
            },
        ),
        migrations.CreateModel(
            name="DailySequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Sequence Number"
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Sequence",
                "verbose_name_plural": "Daily Sequences",
                "indexes": [
                    models.Index(fields=["date"], name="workflows_d_date_1cbb28_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="QueryTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "t_tag",
                    models.CharField(
                        db_index=True,
                        help_text="Format: TYPE-DEPT-YYMMDD-SEQ (e.g., QGD-PD-260122-001)",
                        max_length=50,
                        unique=True,
                        verbose_name="Ticket Tag",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RECEIVED", "Received"),
                            ("ASSIGNED", "Assigned"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("SENDER_BOX", "Sender Box"),
                            ("BIG_HUB", "Big Hub"),
                            ("RECEIVER_BOX", "Receiver Box"),
                            ("TASK_BOX", "Task Box"),
                        ],
                        default="SENDER_BOX",
                        max_length=20,
                        verbose_name="Location",
                    ),
                ),
                (
                    "target_dept_code",
                    models.CharField(
                        help_text="Code of the target department (e.g., 'PD', 'HRTJ')",
                        max_length=10,
                        verbose_name="Target Department Code",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "grabbed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the ticket was grabbed by current owner (5-min rule)",
                        null=True,
                        verbose_name="Grabbed At",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "current_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Current Owner",
                    ),
                ),
                (
                    "source_dept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_tickets",
                        to="profiles.department",
                        verbose_name="Source Department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Query Ticket",
                "verbose_name_plural": "Query Tickets",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["t_tag"], name="workflows_q_t_tag_ca61f6_idx"),
                    models.Index(
                        fields=["status", "location"],
                        name="workflows_q_status_235ae3_idx",
                    ),
                    models.Index(
                        fields=["source_dept", "status"],
                        name="workflows_q_source__ad43d4_idx",
                    ),
                    models.Index(
                        fields=["target_dept_code", "status"],
                        name="workflows_q_target__ca65b5_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="workflows_q_created_7fe61c_idx"
                    ),
                ],
            },
        ),
    ]
