# Generated by Django 6.0.1 on 2026-01-22 14:59

import django.db.models.deletion
import workflows.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QueryAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=workflows.models.attachment_upload_path,
                        verbose_name="File",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Original Filename"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Uploaded At"),
                ),
                (
                    "sequence_letter",
                    models.CharField(
                        blank=True,
                        max_length=1,
                        verbose_name="Sequence Letter (A/B/C...)",
                    ),
                ),
                (
                    "query_ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="workflows.queryticket",
                        verbose_name="Query Ticket",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploaded By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Query Attachment",
                "verbose_name_plural": "Query Attachments",
                "ordering": ["sequence_letter", "uploaded_at"],
            },
        ),
    ]
