# Generated by Django 6.0.1 on 2026-01-22 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_target_dept_code_to_fk(apps, schema_editor):
    """
    Migrate target_dept_code CharField to target_dept ForeignKey.
    Maps existing department codes to Department instances.
    """
    QueryTicket = apps.get_model('workflows', 'QueryTicket')
    Department = apps.get_model('profiles', 'Department')
    
    # Build a mapping of code -> department
    dept_mapping = {dept.code: dept for dept in Department.objects.all()}
    
    # Update each ticket
    for ticket in QueryTicket.objects.all():
        if ticket.target_dept_code and ticket.target_dept_code in dept_mapping:
            ticket.target_dept = dept_mapping[ticket.target_dept_code]
            ticket.save(update_fields=['target_dept'])
        else:
            # If code doesn't exist, try to create a placeholder or use source_dept
            print(f"Warning: No department found for code '{ticket.target_dept_code}' on ticket {ticket.t_tag}")
            # Fall back to source department if target not found
            ticket.target_dept = ticket.source_dept
            ticket.save(update_fields=['target_dept'])


def reverse_migrate_target_dept(apps, schema_editor):
    """
    Reverse migration: populate target_dept_code from target_dept FK.
    """
    QueryTicket = apps.get_model('workflows', 'QueryTicket')
    
    for ticket in QueryTicket.objects.select_related('target_dept').all():
        if ticket.target_dept:
            ticket.target_dept_code = ticket.target_dept.code
            ticket.save(update_fields=['target_dept_code'])


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_create_users_for_employees"),
        ("workflows", "0002_queryattachment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Remove old index on target_dept_code
        migrations.RemoveIndex(
            model_name="queryticket",
            name="workflows_q_target__ca65b5_idx",
        ),
        
        # Step 2: Add new target_dept FK (nullable for now)
        migrations.AddField(
            model_name="queryticket",
            name="target_dept",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="received_tickets",
                to="profiles.department",
                verbose_name="Target Department",
            ),
        ),
        
        # Step 3: Data migration - populate target_dept from target_dept_code
        migrations.RunPython(
            migrate_target_dept_code_to_fk,
            reverse_migrate_target_dept
        ),
        
        # Step 4: Add new index on target_dept
        migrations.AddIndex(
            model_name="queryticket",
            index=models.Index(
                fields=["target_dept", "status"], name="workflows_q_target__c1a37e_idx"
            ),
        ),
        
        # Step 5: Remove old target_dept_code field
        migrations.RemoveField(
            model_name="queryticket",
            name="target_dept_code",
        ),
    ]
