# Generated by Django 6.0.1 on 2026-01-27 11:49

import django.db.models.deletion
import workflows.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_create_users_for_employees"),
        ("workflows", "0003_add_target_dept_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="queryticket",
            name="content_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON storage for dynamic form field values",
                verbose_name="Content Data",
            ),
        ),
        migrations.AlterField(
            model_name="queryticket",
            name="content",
            field=models.TextField(blank=True, verbose_name="Content"),
        ),
        migrations.CreateModel(
            name="QueryType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Purchase Request', 'IT Support', 'Leave Application'",
                        max_length=100,
                        unique=True,
                        verbose_name="Query Type Name",
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="Short code for t_tag generation (e.g., 'PR', 'IT', 'LA')",
                        max_length=20,
                        unique=True,
                        verbose_name="Type Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of this query type",
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive query types cannot be used for new tickets",
                        verbose_name="Is Active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allowed_departments",
                    models.ManyToManyField(
                        help_text="Departments that can receive this type of query",
                        related_name="accepted_query_types",
                        to="profiles.department",
                        verbose_name="Allowed Departments",
                    ),
                ),
            ],
            options={
                "verbose_name": "Query Type",
                "verbose_name_plural": "Query Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="QueryFieldDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Display label (e.g., 'Reason for Purchase')",
                        max_length=100,
                        verbose_name="Field Label",
                    ),
                ),
                (
                    "field_key",
                    models.SlugField(
                        help_text="Key for JSON storage (e.g., 'reason_purchase'). Use lowercase with underscores.",
                        verbose_name="Field Key",
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text (Single Line)"),
                            ("TEXTAREA", "Text (Multi Line)"),
                            ("INTEGER", "Integer Number"),
                            ("DECIMAL", "Decimal Number"),
                            ("DATE", "Date"),
                            ("FILE", "File Upload"),
                            ("BOOLEAN", "Yes/No Checkbox"),
                        ],
                        default="TEXT",
                        max_length=20,
                        verbose_name="Field Type",
                    ),
                ),
                (
                    "required",
                    models.BooleanField(default=True, verbose_name="Required"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Fields are displayed in ascending order",
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "placeholder",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Placeholder Text"
                    ),
                ),
                (
                    "help_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Help Text"
                    ),
                ),
                (
                    "query_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="workflows.querytype",
                        verbose_name="Query Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Query Field Definition",
                "verbose_name_plural": "Query Field Definitions",
                "ordering": ["query_type", "order", "id"],
                "unique_together": {("query_type", "field_key")},
            },
        ),
        migrations.AddField(
            model_name="queryticket",
            name="query_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Dynamic query type definition",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tickets",
                to="workflows.querytype",
                verbose_name="Query Type",
            ),
        ),
        migrations.CreateModel(
            name="TicketAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=workflows.models.dynamic_media_path,
                        verbose_name="File",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Original Filename"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "field_definition",
                    models.ForeignKey(
                        blank=True,
                        help_text="The dynamic field this file belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attachments",
                        to="workflows.queryfielddefinition",
                        verbose_name="Field Definition",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dynamic_attachments",
                        to="workflows.queryticket",
                        verbose_name="Query Ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket Attachment",
                "verbose_name_plural": "Ticket Attachments",
                "ordering": ["created_at"],
            },
        ),
    ]
