# Generated by Django 6.0.1 on 2026-01-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_user_department_assignment"),
        ("workflows", "0004_dynamic_query_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceiverTicket",
            fields=[],
            options={
                "verbose_name": "Item in Receiver Box",
                "verbose_name_plural": "📥 Receiver Box (Ready to Assign)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("workflows.queryticket",),
        ),
        migrations.CreateModel(
            name="SenderTicket",
            fields=[],
            options={
                "verbose_name": "Item in Sender Box",
                "verbose_name_plural": "📤 Sender Box (Waiting for Hub)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("workflows.queryticket",),
        ),
        migrations.AddField(
            model_name="querytype",
            name="creating_departments",
            field=models.ManyToManyField(
                blank=True,
                help_text="Only users from these departments can initiate this query type.",
                related_name="creatable_query_types",
                to="profiles.department",
                verbose_name="Source Departments (Creators) / 谁可以发起",
            ),
        ),
        migrations.AlterField(
            model_name="querytype",
            name="allowed_departments",
            field=models.ManyToManyField(
                help_text="Departments that can receive this type of query",
                related_name="accepted_query_types",
                to="profiles.department",
                verbose_name="Target Departments (Receivers) / 目标部门",
            ),
        ),
    ]
